version: '3'
services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db/redit
      - GROQ_API_KEY=${GROQ_API_KEY}
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=redit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: